version: '3'

services:
  test_db:
    image: postgres
    container_name: clerks-api-postgres-test
    environment:
      - POSTGRES_DB=clerks_api_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  test:
    build: .
    command: "bundle exec rspec"
    volumes:
      - app-storage:/rails/storage
    environment:
      - RAILS_ENV=test
    depends_on:
      - test_db

volumes:
  app-storage: {}
